config/routes.rb
Rails.application.routes.draw do
  root to: redirect('session/signin')

  resource :session, path_names: { new: 'signin' }

  get 'getdata' => 'appointments#owner_appointments', as: 'owner_appointments'
  get '/users/:user_id/appointments/list' => 'appointments#list', as: 'user_appointments_list'
  resources :users do
    resources :appointments
    resources :schedules
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :schedules, foreign_key: :owner_id, dependent: :destroy
  has_many :owner_appointments, class_name: 'Appointment', foreign_key: :owner_id, dependent: :destroy
  has_many :caller_appointments, class_name: 'Appointment', foreign_key: :caller_id, dependent: :destroy

  has_secure_password

  enum gender: [ :male, :female ]
  enum user_type: [ :professional, :client ]

  validates :name, presence: true
  validates :email, presence: true,
                    format: /\A\S+@\S+\z/,
                    uniqueness: { case_sensitive: false }
  validates :gender, inclusion: { in: genders }
  validates :age,
            numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :user_type, presence: true, inclusion: { in: user_types}

  after_create :generate_schedule_cache

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end

  def works_for?(week_day:, hour:)
    Schedule.exist?(owner: self, week_day: week_day, hour: hour)
  end

  def schedule_for(week_day:, hour:)
    works_for?(week_day: week_day, hour: hour) ? schedules.find_by(week_day: week_day, hour: hour) : Schedule.new(owner: self, week_day: week_day, hour: hour)
  end

  def has_an_appointment?(owner:, date:)
    appointment_caller = Rails.cache.fetch(Appointment.cache_key(owner: owner, date: date))
    
    if appointment_caller && owner.id == self.id 
      # User has an appopintment from other user
      true
    elsif appointment_caller == self.id 
      # User has an appointment for the appointment owner 
      true
    end
  end

  def appointment_for(owner:, date:)
    has_an_appointment?(owner: owner, date: date) ? Appointment.find_by(owner: owner, date: date) : Appointment.new(owner: owner, caller: self, owner: owner, date: date)
  end

  def generate_schedule_cache
    1.upto(7).each do |week_day|
      0.upto(23).each do |hour|
        Rails.cache.write(Schedule.cache_key(owner: self, week_day: week_day%7, hour: hour), false)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.with(user: @user).welcome_email.deliver_later
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Thanks for signing up!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Account successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, alert: 'Account successfully deleted!'
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :age, :email, :password, :password_confirmation, :user_type)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/errors", object: @user %>
  <fieldset>
    <ol>
      <li>
        <%= f.label :name, "Full Name" %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li>
        <%= f.label :gender %>
        <%= f.select :gender,
                      User.genders.keys.map { |gender| [gender.titleize, gender] },
                      prompt: "Pick one" %>
      </li>
      <li>
        <%= f.label :age %>
        <%= f.number_field :age, size: 3 %>
      </li>
      <li>
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li>
        <%= f.label :user_type %>
        <%= f.select :user_type,
                      User.user_types.keys.map { |user_type| [user_type.titleize, user_type] },
                      prompt: "Pick one" %>
      </li>
      <li>
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li>
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ol>
    <p>
      <% if @user.new_record? %>
        <%= f.submit "Create Account" %>
      <% else %>
        <%= f.submit "Update Account" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header>
  <h1>Edit Account</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header>
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<header>
  <h1>Sign Up</h1>
</header>

<%= render 'form' %>

app/views/users/show.html.erb
<article>
  <header>
    <h1><%= @user.name %></h1>
    <h2><%= mail_to(@user.email) %></h2>
  </header>
</article>

<footer>
  <nav>
    <% if current_user?(@user) %>
      <%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
      <%= link_to 'Delete Account', @user, 
                  method: :delete, 
                  data: { confirm: 'Are you sure you want to permanently delete your account?' }, 
                  class: 'button' %>
    <% end %>
  </nav>
</footer>