config/routes.rb
Rails.application.routes.draw do
  root to: redirect('session/signin')

  resource :session, path_names: { new: 'signin' }

  get 'getdata' => 'appointments#owner_appointments', as: 'owner_appointments'
  get '/users/:user_id/appointments/list' => 'appointments#list', as: 'user_appointments_list'
  resources :users do
    resources :appointments
    resources :schedules
  end
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  belongs_to :caller, class_name: 'User', foreign_key: :caller_id

  before_validation :valid_appointment?
  after_create :send_create_emails, :write_cache
  after_destroy :send_destroy_emails, :purge_cache

  def destroy_for(current_user)
    if caller == current_user
      destroy
      true
    else
      if owner == current_user
        if Appointment.exists?(owner: owner, date: date)
          destroy
          true
        else
          errors.add(:base, :alert, message: 'You only can modify an appointment from other user (yellow hours)')
          false
        end
      else
        errors.add(:base, :alert, message: 'You only can modify your own appointments (yellow hours)')
        false
      end
    end
  end

  def self.cache_key(owner:, date:)
    owner.id.to_s + '_' + date.year.to_s + date.month.to_s + date.day.to_s + date.hour.to_s
  end

  private

  def valid_appointment?
    return if caller.has_an_appointment?(owner: owner, date: date) && id.present?
    if Rails.cache.exist?(Appointment.cache_key(owner: owner, date: date))
      errors.add(:base, :alert, message: 'You only can take an empty appointment')
    elsif owner.works_for?(week_day: date.wday, hour: date.hour)
      # res
    else
      errors.add(:base, :alert, message: 'You only can take an appointment in green hours')
    end
  end

  def send_create_emails
    UserMailer.with(appointment: self).new_appointment_owner_email.deliver_later
    UserMailer.with(appointment: self).new_appointment_caller_email.deliver_later
  end

  def send_destroy_emails
    UserMailer.with(appointment: self).remove_appointment_caller_email.deliver_later
    UserMailer.with(appointment: self).remove_appointment_owner_email.deliver_later
  end

  def write_cache
    Rails.cache.write(Appointment.cache_key(owner: owner, date: date), caller_id)
  end

  def purge_cache
    Rails.cache.delete(Appointment.cache_key(owner: owner, date: date))
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new(caller_id: params[:user_id])
  end

  def owner_appointments
    @owner = User.find_by(id: params[:owner])
    @page = params[:page].blank? ? 1 : params[:page].to_i
  end

  def create
    @appointment = Appointment.create(appointment_params)
  end

  def update
    @appointment = Appointment.find_by(id: params[:id])
    if @appointment.destroy_for(current_user)
      @appointment = Appointment.new(owner: @appointment.owner, caller: @appointment.caller, date: @appointment.date)
    end
  end

  def index
    @owner = current_user
    @page = params[:page].blank? ? 1 : params[:page].to_i
  end

  def list
    @appointments = current_user.caller_appointments.order(date: :asc)
  end

  def destroy
    appointment = Appointment.find_by(id: params[:id])
    appointment.destroy
    redirect_to user_appointments_list_path(current_user), alert: "Appointment successfuly removed!"
  end

  private

  def appointment_params
    params.require(:appointment).permit(:owner_id, :caller_id, :date)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def appointments_week_days(page)
    days = []

    0.upto(6).each do |week_day|
      days << (Date.today + (page - 1).weeks).beginning_of_week + week_day.days
    end

    days
  end

  def appointments_schedule_class(owner:, caller:, date:)
    if caller.has_an_appointment?(owner: owner, date: date)
      'self-appointment'
    elsif Rails.cache.exist?(Appointment.cache_key(owner: owner, date: date))
      'appointment'
    elsif owner.works_for?(week_day: date.wday, hour: date.hour)
      'active'
    else
      'not-active'
    end

    # if caller.has_an_appointment?(owner: owner, date: date)
    #   'self-appointment'
    # elsif Appointment.exists?(owner: owner, date: date)
    #   'appointment'
    # elsif owner.works_for?(week_day: date.wday, hour: date.hour)
    #   'active'
    # else
    #   'not-active'
    # end
  end

  def appointment_name_to_show(appointment:)
    appointment.caller.name if appointment.id? && appointment.owner.id == current_user.id
  end
end

app/views/appointments/_day.html.erb
<td id='schedule_<%= day.wday %>_<%= hour %>' class="<%= appointments_schedule_class(owner: owner, caller: caller, date: DateTime.new(day.year, day.month, day.day, hour)) %>">
  <%= render partial: 'appointments/form', locals: { appointment: current_user.appointment_for(owner: @owner, date: DateTime.new(day.year, day.month, day.day, hour)) } %>
</td>

app/views/appointments/_form.html.erb
<%= form_with model: [appointment.owner, appointment] do |f| %>
  <%= f.hidden_field :owner_id %>
  <%= f.hidden_field :caller_id %>
  <%= f.hidden_field :date %>
  <%= f.submit appointment_name_to_show(appointment: appointment).to_s unless appointment.new_record? && appointment.owner == current_user %>
<% end %>

app/views/appointments/_owner_appointments.html.erb
<% if @owner %>
  <% days = appointments_week_days(@page) %>
  <table id="table" class="schedule">
    <tr>
      <td></td>
      <% days.each do |day| %>
        <td>
          <%= l(day, format: "%^a %e %b") %>
        </td>
      <% end %>
    </tr>
    <% 0.upto(23).each do |hour| %>
      <tr>
        <td><%= format("%02d:00", hour) %></td>
        <%# OPCIÓ LENTA PERÒ MOLONA %>
        <%#= render partial: 'appointments/day', collection: days, locals: { owner: @owner, caller: current_user, hour: hour } %>
        
        <%# OPCIÓ RÀPIDA %>
        <% days.each do |day| %>
          <td id='schedule_<%= day.wday %>_<%= hour %>' class="<%= appointments_schedule_class(owner: @owner, caller: current_user, date: DateTime.new(day.year, day.month, day.day, hour)) %>">
            <% appointment = current_user.appointment_for(owner: @owner, date: DateTime.new(day.year, day.month, day.day, hour)) %>
            <%= form_with model: [appointment.owner, appointment] do |f| %>
              <%= f.hidden_field :owner_id %>
              <%= f.hidden_field :caller_id %>
              <%= f.hidden_field :date %>
              <%= f.submit appointment_name_to_show(appointment: appointment).to_s unless appointment.new_record? && appointment.owner == current_user %>
            <% end %>
          </td>
        <% end %>

      </tr>
    <% end %>
  </table>
  <% 1.upto(4).each do |page| %>
    <%= link_to page, url_for(params.permit!.merge(page: page)), remote: params[:action] != 'index', class: "#{'active' if page == @page}" %>
  <% end %>
<% end %>

app/views/appointments/create.js.erb
<% if @appointment.id? %>
  var td = document.getElementById('schedule_<%= @appointment.date.wday %>_<%= @appointment.date.hour %>');
  td.classList.remove('active');
  td.classList.add('self-appointment');
  td.innerHTML = "<%= j(render partial: 'appointments/form', locals: { appointment: @appointment }) %>";
<% else %>
  <% @appointment.errors.full_messages.each do |message| %>
    alert("<%= message %>");
  <% end %>
<% end %>

app/views/appointments/index.html.erb
<div id="owner_appointments">
  <%= render partial: 'appointments/owner_appointments' %>
</div>

app/views/appointments/list.html.erb
<% @appointments.each do |appointment| %>
  <div class="appointment_card">
    <p>
      <%= appointment.date.to_s(format = :long) %>
    </p>
    <p>
      <%= appointment.owner.name %>
      <%= button_to "Remove", user_appointment_path(current_user, appointment.id), method:"delete" %>
    </p>
  </div>
<% end %>

app/views/appointments/new.html.erb
<span>Appointment for</span>
<%= select_tag :owner,
      options_from_collection_for_select(User.professional.where.not(id: current_user.id), "id", "name"), data: { remote: true, url: url_for(controller: 'appointments', action: 'owner_appointments') }, prompt: 'Select one'
%>
<div id="owner_appointments">
  <%= render partial: 'appointments/owner_appointments' %>
</div>

app/views/appointments/owner_appointments.js.erb
var td = document.getElementById("owner_appointments");
td.innerHTML = "<%= j( render partial: 'appointments/owner_appointments' ) %>";

app/views/appointments/update.js.erb
<% if @appointment.new_record? %>
  var td = document.getElementById('schedule_<%= @appointment.date.wday %>_<%= @appointment.date.hour %>');
  td.classList.remove('self-appointment');
  td.classList.add('active');
  td.innerHTML = "<%= j(render partial: 'appointments/form', locals: { appointment: @appointment }) %>";
<% else %>
  <% @appointment.errors.full_messages.each do |message| %>
    alert("<%= message %>");
  <% end %>
<% end %>