config/routes.rb
Rails.application.routes.draw do
  root to: redirect('session/signin')

  resource :session, path_names: { new: 'signin' }

  get 'getdata' => 'appointments#owner_appointments', as: 'owner_appointments'
  get '/users/:user_id/appointments/list' => 'appointments#list', as: 'user_appointments_list'
  resources :users do
    resources :appointments
    resources :schedules
  end
end

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2018
    <%= link_to 'DigitalYOU','http://digitalyou.es' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div>
    <nav>
      <h1>Appointex</h1>
      <p>
        <% if current_user %>
          <%= link_to current_user.name, current_user %>
          <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
        <% else %>
          <%= link_to 'Sign Up', new_user_path, class: 'button' %>
          <%= link_to 'Sign In', new_session_path, class: 'button' %>
        <% end %>
      </p>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
  <aside id="sidebar">
    <nav>
      <% if current_user %>
        <ul>
          <% if current_user_professional? %>
            <li>
              <%= link_to 'My Schedule', user_appointments_path(current_user) %>
            </li>
            <li>
              <%= link_to 'Configuration', user_schedules_path(current_user) %>
            </li>
          <% end %>
          <li>
            <%= link_to 'My Appointments', user_appointments_list_path(current_user) %>
          </li>
          <li>
            <%= link_to 'New Appointment', new_user_appointment_path(user_id: current_user.id) %>
          </li>
        </ul>
      <% end %>
    </nav>
  </aside>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <% if flash[:notice] %>
      <p class="flash notice">
        <%= flash[:notice] %>
      </p>
    <% end %>

    <% if flash[:alert] %>
      <p class="flash alert">
        <%= flash[:alert] %>
      </p>
    <% end %>
    
    <%= render 'layouts/sidebar' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>